### ISSUE TITLE
[bug]/[minor oversight] missing research dependencies for a few projects 

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [AndroidQuazar/VanillaFactionsExpanded-Classical#1]
Hey I have been doing some "start with low tech" runs along with semi-random research and I have found a few inconsistencies of the dependencies for a few projects

 `VFEC_TemperatureControl` does not depend on `PassiveCooler`

`VFEC_Mosaics`, `VFEC_Thermaebath`, `VFEC_DramaAndComedy`, `VFEC_CementMaking`, `VFEC_HeavyShieldMaking`, `VFEC_LegionnaireArmor`, `VFEC_CenturionArmor`  does not depend on `Stonecutting`

`VFEC_BronzeWorking` does not depend on `Smithing`

Should i make a Pull Request?

**Comment by Kallinteris-Andreas** [comment]
Note `VFEC_LegionaryArmaments` could rely on `Smithing` because of the weapons it provides, or it could be left with no dependency because it provides a tent

**Comment by legodude17** [comment]
This is intentional. The researches are not meant to be in the traditional tree, instead being unlocked by gaining favor with senators.
